import { type NextPage } from "next";
import Head from "next/head";
import styles from "../index.module.css";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>Slug page</h1>
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
